### ISSUE TITLE
Mixed results when applying to my own dataset

### ISSUE THREAD

**Issue by sklipnoty** [andrewssobral/vehicle_detection_haarcascades#1]
Hello 

First I would like to say thank you for putting this code online.

However I have some questions if I want to use this method do I have to re-train the haar cascade classifier on my own dataset? Or can I use your trained cascade?

The results I'm getting, using your trained data are the following;

Positive;

![image](https://cloud.githubusercontent.com/assets/1823862/15216217/97a689c8-1856-11e6-8484-9e7512ab14a5.png)

Negative;

![image](https://cloud.githubusercontent.com/assets/1823862/15216271/c8f8b262-1856-11e6-92a1-dc40654f7e03.png)

Could you explain why I'm getting mixed results?

Thx in advance!

My regards

Sklip

**Comment by andrewssobral** [comment]
Hi @sklipnoty 
Yes you can re-train the haar cascades using your own dataset.
The pre-trained model used in this project have some limitations, causing these mixed results.
If you want a more robust approach, I recommend you to see the recent advances on deep learning for object detection. I'm planing to do this in the future and I will let you updated about this.
Best regards
Andrews

**Comment by chandanemmi** [comment]
When I use your model on my dataset, I m getting mixed result. 
Can you please help me out to over come this issue?.

**Comment by chandanemmi** [comment]
Not dataset , it's video.
