### ISSUE TITLE
Can't get it working with OpenCV 3.1.0

### ISSUE THREAD

**Issue by HassanSE** [andrewssobral/vehicle_detection_haarcascades#2]
Hello Andrew,

Thank you for sharing this project. It's great help. I've recently started working with OpenCV for vehicle detection. Unfortunately, I can't make this project functional with OpenCV. I've tried version 3.1.0 as well as 2.4.12. Program exists with statement 

> "Usage ... cascade.xml video.avi"

Please let me know how to fix this. Thank you.

**Comment by andrewssobral** [comment]
Hi @HassanSE , unfortunately this code does not work on OpenCV 3.x only with OpenCV 2.4.x
I compiled sucessfully with OpenCV 2.4.13 and it works fine in my machine, however if it still not working you can try my latest Docker image, please see:
https://github.com/andrewssobral/vehicle_detection_haarcascades#docker-image
