### ISSUE TITLE
identifying individual object

### ISSUE THREAD

**Issue by nisarg09** [andrewssobral/vehicle_detection_haarcascades#3]
Hi..
I have implemented the same and getting results as you have shown. The issue here is I need to identify each individual object in each sequence of frame in video(input source). Can you tell me please how to identify/track particular object in consecutive frames from the list of rectangles from given output?

**Comment by andrewssobral** [comment]
Hi @nisarg09 sorry for my late response. 

For object tracking you can use a:
* 1. **very basic approach**: by a blob tracker algorithm such as [cvBlob](https://code.google.com/archive/p/cvblob/) or [OpenCVBlobsLib](http://opencvblobslib.github.io/opencvblobslib/).
* 2. **traditional approach**: by a tracker algorithm, please see [Introduction to OpenCV Tracker](http://docs.opencv.org/3.1.0/d2/d0a/tutorial_introduction_to_tracker.html). See also [Tracker Algorithms](http://docs.opencv.org/3.0-beta/modules/tracking/doc/tracker_algorithms.html).

For object recognition (e.g. type of the vehicle: car,bus,truck,etc) you will need to build your own classifier. There are several ways to do this, some of them are:
* 1. **very basic approach**: you use a background subtraction algorithm (e.g. [bgslibrary](https://github.com/andrewssobral/bgslibrary)) and classify the objects by its blob size (see [simple_vehicle_counting](https://github.com/andrewssobral/simple_vehicle_counting)).
* 2. **traditional approach**: giving the bounding box of the detected vehicles, you extract its features and use a secondary classifier (such as [svm](http://docs.opencv.org/2.4/doc/tutorials/ml/introduction_to_svm/introduction_to_svm.html)) for vehicle type classification.
* 3. **more robust approach**: use the recent advances on deep convolutional neural networks (Deep CNNs, such as [caffe](http://caffe.berkeleyvision.org/), [tiny-dnn](https://github.com/tiny-dnn/tiny-dnn), etc) for automatically feature extraction and classification. 

However, for both options 2 and 3, you will need to build your own image dataset (with hundreds of images) for training, validation and test.
