### ISSUE TITLE
Report file

### ISSUE THREAD

**Issue by quyduy** [andrewssobral/vehicle_detection_haarcascades#4]
Thank you for sharing the code. COuld you please let me know how i can get the report after running the code.
Regards

**Comment by andrewssobral** [comment]
Hi @quyduy 
Thank you too for enjoying the algorithm source code.
What do you mean precisely by "getting report"? This is about how many vehicles were detected?

**Comment by quyduy** [comment]
Hi Andrewssobral,

Yes, if i want to know how many cars were detected and the speed of each car, what do ia have to do.

Thank you very much for your support.

**Comment by andrewssobral** [comment]
Hi @quyduy you have two special cases:
1. for the vehicle counting problem, you need a multi-object tracking algorithm. Some nice algorithms for multiple tracking are [Multiple Hypothesis Tracking](https://github.com/WeatherGod/MHT) and [Particle Filter](https://github.com/NewProggie/Particle-Filter).
2. for estimating the vehicle speed you can use the centroid of each vehicle (given by a tracker) under some non-linear transformation or regression. However, you may need the real vehicle speed for calibration. You can follow this post [Real-time speed estimation of cars with OpenCV](http://www.amphioxus.org/content/real-time-speed-estimation-cars) wrote by Armin.
