### ISSUE TITLE
Problem with docker vncserver

### ISSUE THREAD

**Issue by Bodiva** [andrewssobral/vehicle_detection_haarcascades#5]
Hello andrewssobral,

thanks for your codes.
I'm looking on your docker side,  there is a error about vncserver.

Window manager warning: Log level 16: metacity: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.

Could you help me for this case?

thanks,
Yunbo

**Comment by andrewssobral** [comment]
Hi @Bodiva 
Do you have followed this sequence?
```
docker pull andrewssobral/vehicle_detection_tracking_counting
docker run -it -p 5901:5901 andrewssobral/vehicle_detection_tracking_counting bash
root@containerid:/# /usr/bin/vncserver :1 -geometry 1280x800 -depth 24 && tail -f /root/.vnc/*:1.log
```
and next in your PC:
* open vncviewer
* connection: **127.0.0.1:5901**
* password: **password**

I cleaned my docker and followed the same instructions, and it works well in my PC.
