### ISSUE TITLE
vehicle_detection_haarcascades execution: permission denied.

### ISSUE THREAD

**Issue by canny07** [andrewssobral/vehicle_detection_haarcascades#6]
Hi,

I'm not sure why is it happening? I tried many things and searched extensively, but couldn't find any solution to the problem.
The problem is: while running the demo `run_vehicle_detection_video1.sh,` I'm getting permission denied in the terminal.
You had suggested `~/vehicle_detection_haarcascades/run_vehicle_detection_video1.sh` , which wasn't working. I tried `./run_vehicle_detection_video1.sh`, and `sudo sh ./run_vehicle_detection_video1.sh`, the former gives `bash: ./run_vehicle_detection_video2.sh: Permission denied`, while the latter has output `./run_vehicle_detection_video2.sh: 2: ./run_vehicle_detection_video2.sh: ./build/vehicle_detection_haarcascades: Permission denied`

Can you suggest what to do?

**Comment by andrewssobral** [comment]
Hi @canny07 you need to change the execution permission of the shell script files as follows:
```
chmod +x run_vehicle_detection_video1.sh
chmod +x run_vehicle_detection_video2.sh
```
Please, see:
http://askubuntu.com/questions/409025/permission-denied-when-running-sh-scripts
