### ISSUE TITLE
Questions and Assistance needed for your Vehicle Detection program.

### ISSUE THREAD

**Issue by ahowe444** [andrewssobral/vehicle_detection_haarcascades#7]
Hello Andrew,
I am representing a group of high school students in a class called Engineering Design and Development. We are interested in using your program to detect cars to protect cyclists on the road. We have experimented with the Xbox Kinect and believe that we could use your program to help us detect cars with a camera mounted on the back of a bike for testing purposes. We have ran into some issues running your code. We are using Visual Studio 2015 and the correct version of OpenCV that you specified, however, when we open your project file in visual studio, it does not build. In some cases, the #include <...> is not able to find the opencv.hpp header file and in other cases the program is not able to find an .exe file and throws an error. We installed OpenCV in the C:\ drive and believe we have the correct directory in the #include<...> 
This is the error we were receiving regarding the #include:
https://msdn.microsoft.com/en-us/library/et4zwx34.aspx

We would greatly appreciate some advice or guidance on what we are doing wrong and how we can use your program. 

Ultimately we would like to build off of it to support a live feed from a webcam which we will analyze real time through a Arduino, using OpenCV.

**Comment by andrewssobral** [comment]
Hi @ahowe444 thank you for your interest in this project.
In your case, I think the problem is that OpenCV 2.4.x does not have compatibility with VS 2015.
You need to downgrade to VS 2013.
