### ISSUE TITLE
Unable to link to OpenCV

### ISSUE THREAD

**Issue by absnaik810** [andrewssobral/vehicle_detection_haarcascades#9]
I am trying to connect this to OpenCV to run it in Ubuntu.  However, I am unable to establish this connection.  The details of the error are included in the image below:

![capture](https://cloud.githubusercontent.com/assets/7829674/24277860/59b6cc46-1016-11e7-8f82-8734c0de77c3.JPG)

It mentions CMAKE_MODULE_PATH, which I was unable to find in the project repository.  Could you please help me get around this issue?  I am doing this as an academic project and would appreciate your prompt help.

Thanks.

**Comment by andrewssobral** [comment]
Hi @absnaik810 , it seems that your opencv is not well installed.
You can use the following tutorial for help:
http://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/
replacing OpenCV 3.1.0 by **OpenCV 2.4.13.2** (last release). 
You can skip the python step if you don't need.
Usually, at the end of compiling OpenCV you need to do:
```
$ sudo make install
$ sudo ldconfig 
```
and check by:
```
$ pkg-config --modversion opencv
```
Hope this help you.

**Comment by absnaik810** [comment]
Hi Andrew,

Thanks for your reply.  I tried following the steps in the link that you had provided, but now I am facing a new error that says _it is able to find OpenCV, but OpenCV_FOUND is set to FALSE due to which OpenCV is not found_.  Do you have any suggestions about how we could go about solving this error?

The screenshot of the exact error that we faced is below:

![capture](https://cloud.githubusercontent.com/assets/7829674/24936473/a16bf1de-1ef7-11e7-85da-0006ef250206.JPG)

**Comment by andrewssobral** [comment]
Hi @absnaik810 ,
What is the output when you run?
```
$ pkg-config --modversion opencv
```

**Comment by absnaik810** [comment]
It says that it was unable to find the package.  Does this mean that it is incorrectly installed?  Note that I installed it in a virtual environment and Step#6 in the linked webpage did run successfully.
